version: '3.8'

services:
  evadental-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: evadental-api
    ports:
      - "8000:8000"
    environment:
      - MODEL_PATH=/app/models/best.pt
      - CONFIDENCE_THRESHOLD=0.25
      - IOU_THRESHOLD=0.45
    volumes:
      - ../models:/app/models:ro
      - ../data:/app/data:ro
      - ./output:/app/output
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'

  # Service optionnel pour le monitoring
  nginx:
    image: nginx:alpine
    container_name: evadental-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - evadental-api
    restart: unless-stopped
    profiles:
      - production

volumes:
  models:
  data:
  output:
